# ----------------
# Verbose settings
# ----------------
/control/verbose 2
/run/verbose 2

#/tracking/verbose 2

# HepRepFile diriver
#/vis/open HepRepXML

# OpenGL driver
/vis/open OGL 600x400
#/vis/open OGL 3840x2160


# qt driver
#/vis/open qt

# Add world volume
/vis/drawVolume

# Visualise geometry
/vis/viewer/flush

# Set camera angle for OGLIX driver
/vis/viewer/zoom 1.5
/vis/viewer/set/viewpointThetaPhi 91 178
/vis/viewer/set/viewpointThetaPhi 45 45

# Add trajectories to the visualization.
/vis/scene/add/trajectories

# Accumulate multiple events in one picture.
/vis/scene/endOfEventAction accumulate -1

# Trajectory colouring scheme
/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/set -1 red
#/vis/modeling/trajectories/drawByCharge-0/set 1 blue
#/vis/modeling/trajectories/drawByCharge-0/set 0 white

# # To draw neutrinos only
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
# /vis/filtering/trajectories/particleFilter-0/add anti_nu_e
# /vis/filtering/trajectories/particleFilter-0/add nu_e
# #
# # To not draw neutrinos
#/vis/filtering/trajectories/particleFilter-0/invert true

# To draw neutrins and gammas only
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/add neutron

#/gun/particle ion
#/gun/ion 95 241

/run/initialize
#
/process/list
/run/setCut 0.001 mm
#/process/eLoss/StepFunction 0.1 10 um
#/vis/disable
#/run/beamOn 100000000
#/run/beamOn 10000000
#/run/beamOn 1000
#/run/beamOn 10

# Create logo
/run/beamOn 100
/vis/viewer/set/viewpointThetaPhi 0 0
/vis/viewer/zoom 2
